"""Type stubs for the compiled half of fasti.

Date positions are spelled `datetime.date` outright. Note that a type
checker cannot reject a `datetime.datetime` there: `datetime` subclasses
`date`, so it type-checks. The runtime rejects it.
"""

import datetime
from collections.abc import Iterable, Iterator
from fractions import Fraction
from typing import final

class FastiError(ValueError):
    """Every refusal the crate's `TimeError` names. Type mistakes raise `TypeError`."""

@final
class BusinessDayConvention:
    UNADJUSTED: BusinessDayConvention
    FOLLOWING: BusinessDayConvention
    MODIFIED_FOLLOWING: BusinessDayConvention
    PRECEDING: BusinessDayConvention
    MODIFIED_PRECEDING: BusinessDayConvention
    def __new__(cls, spelling: BusinessDayConvention | str) -> BusinessDayConvention: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[str]]: ...

@final
class Weekday:
    MON: Weekday
    TUE: Weekday
    WED: Weekday
    THU: Weekday
    FRI: Weekday
    SAT: Weekday
    SUN: Weekday
    def __new__(cls, spelling: Weekday | str) -> Weekday: ...
    def get(self) -> int: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[str]]: ...

@final
class Frequency:
    ANNUAL: Frequency
    SEMIANNUAL: Frequency
    EVERY_FOURTH_MONTH: Frequency
    QUARTERLY: Frequency
    BIMONTHLY: Frequency
    MONTHLY: Frequency
    EVERY_FOURTH_WEEK: Frequency
    BIWEEKLY: Frequency
    WEEKLY: Frequency
    DAILY: Frequency
    def __new__(cls, spelling: Frequency | str) -> Frequency: ...
    def per_year(self) -> int: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[str]]: ...

@final
class WeekendShift:
    NONE: WeekendShift
    FORWARD: WeekendShift
    SUN_FORWARD: WeekendShift
    SAT_BACK_SUN_FORWARD: WeekendShift
    def __new__(cls, spelling: WeekendShift | str) -> WeekendShift: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[str]]: ...

@final
class EasterMethod:
    WESTERN: EasterMethod
    ORTHODOX: EasterMethod
    def __new__(cls, spelling: EasterMethod | str) -> EasterMethod: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[str]]: ...

@final
class DateGenerationRule:
    FORWARD: DateGenerationRule
    BACKWARD: DateGenerationRule
    ZERO: DateGenerationRule
    def __new__(cls, spelling: DateGenerationRule | str) -> DateGenerationRule: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[str]]: ...

@final
class Period:
    ZERO: Period
    @staticmethod
    def days(n: int) -> Period: ...
    @staticmethod
    def weeks(n: int) -> Period: ...
    @staticmethod
    def months(n: int) -> Period: ...
    @staticmethod
    def years(n: int) -> Period: ...
    @staticmethod
    def from_frequency(frequency: Frequency | str) -> Period: ...
    @property
    def unit(self) -> str: ...
    def length(self) -> int: ...
    def is_zero(self) -> bool: ...
    def normalized(self) -> Period: ...
    def frequency(self) -> Frequency: ...
    def __neg__(self) -> Period: ...
    def __mul__(self, n: int) -> Period: ...
    def __rmul__(self, n: int) -> Period: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[str, int]]: ...

@final
class Rule:
    @staticmethod
    def fixed(
        month: int,
        day: int,
        *,
        shift: WeekendShift | str | None = None,
        years: tuple[int | None, int | None] | None = None,
    ) -> Rule: ...
    @staticmethod
    def nth_weekday(
        n: int,
        weekday: Weekday | str,
        month: int,
        *,
        years: tuple[int | None, int | None] | None = None,
    ) -> Rule: ...
    @staticmethod
    def last_weekday(
        weekday: Weekday | str,
        month: int,
        *,
        years: tuple[int | None, int | None] | None = None,
    ) -> Rule: ...
    @staticmethod
    def easter(
        days: int,
        *,
        method: EasterMethod | str | None = None,
        years: tuple[int | None, int | None] | None = None,
    ) -> Rule: ...
    @staticmethod
    def one_off(date: datetime.date) -> Rule: ...
    def is_holiday(self, date: datetime.date) -> bool: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[tuple[object, ...]]]: ...

@final
class Calendar:
    def __new__(
        cls,
        name: str,
        weekend: Iterable[Weekday | str] = (),
        rules: Iterable[Rule] = (),
    ) -> Calendar: ...
    @property
    def name(self) -> str: ...
    @property
    def weekend(self) -> tuple[Weekday, ...]: ...
    def with_name(self, name: str) -> Calendar: ...
    def with_weekend(self, weekend: Iterable[Weekday | str]) -> Calendar: ...
    def with_rule(self, rule: Rule) -> Calendar: ...
    def union(self, other: Calendar) -> Calendar: ...
    def is_weekend(self, date: datetime.date) -> bool: ...
    def is_holiday(self, date: datetime.date) -> bool: ...
    def is_business_day(self, date: datetime.date) -> bool: ...
    def business_days(
        self, start: datetime.date, end: datetime.date
    ) -> list[datetime.date]: ...
    def holidays(self, start: datetime.date, end: datetime.date) -> list[datetime.date]: ...
    def first_business_day_of_month(self, date: datetime.date) -> datetime.date | None: ...
    def last_business_day_of_month(self, date: datetime.date) -> datetime.date | None: ...
    def next_business_day(self, date: datetime.date) -> datetime.date | None: ...
    def prev_business_day(self, date: datetime.date) -> datetime.date | None: ...
    def adjust(
        self, date: datetime.date, convention: BusinessDayConvention | str
    ) -> datetime.date: ...
    def advance(
        self,
        date: datetime.date,
        period: Period | Frequency | str,
        convention: BusinessDayConvention | str,
        end_of_month: bool = False,
    ) -> datetime.date: ...
    def __hash__(self) -> int: ...
    def __reduce__(
        self,
    ) -> tuple[object, tuple[object, list[tuple[str, object]]]]: ...

@final
class Generation:
    def __new__(
        cls, tenor: Period | Frequency | str, end_of_month: bool
    ) -> Generation: ...
    @property
    def tenor(self) -> Period: ...
    @property
    def end_of_month(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[str, int, bool]]: ...

@final
class Schedule:
    def __new__(
        cls,
        effective: datetime.date,
        termination: datetime.date,
        tenor: Period | Frequency | str,
        calendar: Calendar,
        *,
        convention: BusinessDayConvention | str | None = None,
        termination_convention: BusinessDayConvention | str | None = None,
        rule: DateGenerationRule | str | None = None,
        end_of_month: bool = False,
        first_date: datetime.date | None = None,
        next_to_last_date: datetime.date | None = None,
    ) -> Schedule: ...
    @staticmethod
    def from_dates(dates: Iterable[datetime.date]) -> Schedule: ...
    def dates(self) -> list[datetime.date]: ...
    def periods(self) -> list[tuple[datetime.date, datetime.date]]: ...
    def reference_periods(self) -> list[tuple[datetime.date, datetime.date]]: ...
    def generation(self) -> Generation | None: ...
    def previous_date(self, ref_date: datetime.date) -> datetime.date | None: ...
    def next_date(self, ref_date: datetime.date) -> datetime.date | None: ...
    def lower_bound(self, ref_date: datetime.date) -> datetime.date | None: ...
    def after(self, cutoff: datetime.date) -> Schedule: ...
    def until(self, cutoff: datetime.date) -> Schedule: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> datetime.date: ...
    def __iter__(self) -> Iterator[datetime.date]: ...
    def __hash__(self) -> int: ...
    def __reduce__(
        self,
    ) -> tuple[object, tuple[object, list[tuple[str, object]]]]: ...

@final
class DayCount:
    @staticmethod
    def act_360() -> DayCount: ...
    @staticmethod
    def act_365_fixed() -> DayCount: ...
    @staticmethod
    def act_act_isda() -> DayCount: ...
    @staticmethod
    def act_act_icma(frequency: Frequency | str) -> DayCount: ...
    @staticmethod
    def thirty_360_bond() -> DayCount: ...
    @staticmethod
    def thirty_360_us() -> DayCount: ...
    @staticmethod
    def thirty_360_european() -> DayCount: ...
    @staticmethod
    def thirty_360_isda(termination: datetime.date) -> DayCount: ...
    def name(self) -> str: ...
    def day_count(self, start: datetime.date, end: datetime.date) -> int: ...
    def year_fraction(self, start: datetime.date, end: datetime.date) -> Fraction: ...
    def bind(self, schedule: Schedule) -> DayCount: ...
    def year_fraction_with_reference(
        self,
        start: datetime.date,
        end: datetime.date,
        ref_start: datetime.date,
        ref_end: datetime.date,
    ) -> Fraction: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[tuple[object, ...]]]: ...

def easter_sunday(year: int, method: EasterMethod | str | None = None) -> int: ...
def easter_monday(year: int, method: EasterMethod | str | None = None) -> int: ...

# The registry the `fasti.calendars` package is built from, and the
# pickle hooks every __reduce__ names.
def _builtin(name: str) -> Calendar: ...
def _rebuild_calendar(origin: object, ops: list[object]) -> Calendar: ...
def _rebuild_daycount(state: tuple[object, ...]) -> DayCount: ...
def _rebuild_generation(unit: str, length: int, end_of_month: bool) -> Generation: ...
def _rebuild_period(unit: str, length: int) -> Period: ...
def _rebuild_rule(state: tuple[object, ...]) -> Rule: ...
def _rebuild_schedule(origin: object, ops: list[object]) -> Schedule: ...
